--- #YAML:1.0
name:                Coro
version:             4.51
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    AnyEvent:                      2.7
    EV:                            1.3
    Event:                         1.06
    IO::AIO:                       2.3
    Scalar::Util:                  0
    Storable:                      2.15
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3

configure_requires:
  Event: 1.06
  EV: 1.3
    
