# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Coro
version:      1.0
version_from: Coro.pm
installdirs:  site
requires:
    Event:                         0.86
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
