# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Coro
version:      3.1
version_from: Coro.pm
installdirs:  site
requires:
    AnyEvent:                      2.1
    Event:                         0.86
    IO::AIO:                       1.6
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
