#!/usr/bin/perl

use Coro::Process;

$p = 2;

sub p1 : Coro {
   for (0..9) {
      print "p1: $_\n";
      yield;
   }
   $p--;
}

sub p2 : Coro {
   for (10..23) {
      print "p2: $_\n";
      yield;
   }
   $p--;
}

eval {
   yield while $p;
};



