#!/usr/bin/perl

use Coro;
use Coro::Event;
use Coro::LWP; # should be use'd as early as possible
use LWP::Simple;

$SIG{PIPE} = 'IGNORE';

async {
   print "hi2\n";
   get "http://www.google.de/";
   print "ho2\n";
};

async {
   print "hi\n";
   get "http://www.yahoo.com/";
   print "ho\n";

};

loop;

